module.exports = {
    cmd: 'check',
    desc: 'Check if number exists + Scan neighbors',
    run: async ({ sock, m, args, reply }) => {
        // 1. Get the Target Number
        if (!args[0]) return reply('❌ Please provide a number.\nExample: .check +923367307471');

        // Clean the number (remove + and spaces)
        const inputNumber = args.join('').replace(/[^0-9]/g, '');
        const targetInt = parseInt(inputNumber);

        if (isNaN(targetInt)) return reply('❌ Invalid number format.');

        await reply(`🔍 *Scanning Network...*\nTarget: ${inputNumber}\nAlgorithm: Neighborhood Search (±10)`);

        // 2. Prepare the List (Target + Increments + Decrements)
        // We will scan the target, plus 5 numbers UP and 5 numbers DOWN.
        const numbersToCheck = [];
        const range = 10; // Check 10 neighbors (5 up, 5 down)

        // Add Decrements (Previous numbers)
        for (let i = range; i > 0; i--) {
            numbersToCheck.push((targetInt - i).toString());
        }
        
        // Add Target
        numbersToCheck.push(inputNumber);

        // Add Increments (Next numbers)
        for (let i = 1; i <= range; i++) {
            numbersToCheck.push((targetInt + i).toString());
        }

        try {
            // 3. Perform Bulk Check
            // We format them as JIDs for the API
            const jidList = numbersToCheck.map(n => n + '@s.whatsapp.net');
            
            // Query WhatsApp Server
            const results = await sock.onWhatsApp(jidList);
            
            if (!results || results.length === 0) {
                return reply('❌ No valid WhatsApp accounts found in this range.');
            }

            // 4. Filter & Sort Results
            const activeNumbers = results
                .filter(r => r.exists)
                .map(r => r.jid.split('@')[0]);

            // 5. Build Report
            let report = `📡 *NETWORK CHECK REPORT*\n`;
            report += `🎯 *Target:* ${activeNumbers.includes(inputNumber) ? '✅ ACTIVE' : '❌ NOT REGISTERED'}\n`;
            report += `--------------------------------\n`;
            report += `🔍 *Neighbors Found (${activeNumbers.length}):*\n`;

            activeNumbers.forEach(num => {
                if (num === inputNumber) return; // Skip target in list
                
                // Visualize if it's an increment or decrement
                const diff = parseInt(num) - targetInt;
                const tag = diff > 0 ? `(+${diff})` : `(${diff})`;
                
                report += `📞 ${num} ${tag}\n`;
            });

            report += `\n_Generated by Cosmic Hacker X_`;

            // Send Final Result
            await reply(report);

        } catch (e) {
            console.error(e);
            reply('❌ Error during scan: ' + e.message);
        }
    }
};
